agent/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dashboard.urls')),
    path('user/',include('user.urls')),
    path('accounts/', include('allauth.urls')), #Allauth
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path,include
from dashboard import views
app_name = "dashboard"
urlpatterns = [
    path('', views.home, name="home"),
    path('scholarship/', views.scholarship, name="scholarship"),
    path('scholarship_view/<id>/', views.scholarship_view, name="scholarship_view"),
    path('scholarship_edit/<id>/', views.scholarship_edit, name="scholarship_edit"),
]

user/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from user import views

app_name = "user"
urlpatterns = [
    path('signin/', auth_views.LoginView.as_view(template_name =  'user/signin.html'), name='sign_in'),
    path('signout/', auth_views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='sign_out'),
	path('profile/<id>', views.profile, name="profile"),
	path('featured/', views.featured, name="featured"),
    #path('signup/', user_views.sign_up, name='sign_up'),

]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from user.models import UserDetail
# Create your models here.

class University(models.Model):
	university = models.CharField(max_length=100)
	city = models.CharField(max_length=50)
	tuition = models.IntegerField(default=0)
	accomodation = models.IntegerField(default=0)
	about = models.TextField(default="")
	logo = models.ImageField(upload_to='logo/', blank=False)

	def __str__(self):
		return self.university
		
class Scholarship(models.Model):
	SCHOLARSHIP_CHOICES = (
        ('F', 'Full Scholarship'),
        ('P', 'Partial Scholarship'),
    )



	university = models.ForeignKey(University,on_delete=models.CASCADE)
	tuition_after_schol = models.IntegerField(default=0)
	accomodation_after_schol = models.IntegerField(default=0)
	stipend = models.IntegerField(default=0)
	agent = models.ForeignKey(User, on_delete = models.CASCADE)
	schol_type = models.CharField(max_length=20, choices=SCHOLARSHIP_CHOICES, default="P")
	service_charge = models.IntegerField(default=500)

	def __str__(self):
		return str(self.university) + " - " + str(self.agent)

	def get_absolute_url(self):
		return reverse('dashboard:scholarship_view', kwargs={'id': self.id
        })

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class UserDetail(models.Model):
	USER_CHOICES = (
        ('A', 'Agent'),
        ('S', 'Student'),)


	image = models.ImageField(upload_to='profile_pic/', blank=False)
	user_type = models.CharField(max_length=20, choices=USER_CHOICES, default="S")
	user = models.OneToOneField(User,on_delete=models.CASCADE,related_name="user_detail")
	country = models.CharField(max_length=100, default="China")
	featured = models.BooleanField(default=False)

	def __str__(self):
		return self.user.username

	def get_absolute_url(self):
		return reverse('user:profile', kwargs={'id': self.id
        })

dashboard/forms.py
from django import forms
from dashboard.models import Scholarship

class ScholarshipEditForm(forms.ModelForm):
	class Meta:
		model = Scholarship
		fields = ['university', 'tuition_after_schol', 'accomodation_after_schol', 'stipend', 'schol_type', 'service_charge']

dashboard/views.py
from django.shortcuts import render, redirect
from dashboard.models import Scholarship, University
from dashboard.forms import ScholarshipEditForm
from django.core.paginator import Paginator
# Create your views here.
def home(request):
	context = {

	}
	return render(request, "dashboard/home.html",context)

def scholarship(request):
	scholarships = Scholarship.objects.all().order_by("-id")
	paginator = Paginator(scholarships, 3) # Show 25 contacts per page
	page = request.GET.get('page')
	schol = paginator.get_page(page)

	context = {
	'scholarships':schol
	}
	return render(request, "dashboard/scholarship.html",context)

def scholarship_view(request,id):
	scholarship = Scholarship.objects.get(id=id)
	university = University.objects.get(university = scholarship.university)
	context={
	'scholarship':scholarship,
	'university' :university
	}
	return render(request, "dashboard/scholarship_view.html",context)

def scholarship_edit(request,id):
	form = ScholarshipEditForm(instance = Scholarship.objects.get(id=id))
	if request.method=="POST":
		form = ScholarshipEditForm(request.POST,  instance = Scholarship.objects.get(id=id))
		if form.is_valid():
			form.save()
			return redirect("/scholarship/")
	context={
	'form':form
	}
	return render(request, "dashboard/scholarship_edit.html",context)

user/views.py
from django.shortcuts import render
from user.models import UserDetail
from dashboard.models import Scholarship
from django.contrib.auth.models import User

# Create your views here.
def profile(request,id):
	details = UserDetail.objects.get(id=id)
	try:
		scholarships = Scholarship.objects.filter(agent = details.user)
	except:
		scholarships=""
	context={
	'details':details,
	'scholarships':scholarships
	}
	return render(request,"user/profile.html",context)

def featured(request):
	try:
		featured = UserDetail.objects.filter(featured=True)
		context={
		'featured':featured
		}
	except:
		context={'featured':None}
		
	return render(request,"user/featured.html",context)

templates/basic/navbar.html
{% url 'dashboard:home' as home_url %}
{% url 'dashboard:scholarship' as scholarship_url %}

<nav class="navbar navbar-expand-lg navbar-dark">
  <a class="navbar-brand" href="#">letsrise</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li {%if request.path == home_url%}  class="nav-item active" {%endif%}>
            <a class="nav-link" href="{%url 'dashboard:home'%}" id="home">Home</a>
      </li>
   
      <li {%if request.path == scholarship_url%}  class="nav-item active" {%endif%}>
        <a class="nav-link" href="{%url 'dashboard:scholarship'%}">Scholarship</a>
      </li>
     
    </ul>
     {%if not user.is_authenticated%}
      <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{%url 'user:sign_in'%}">Sign In</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Sign Up</a>
      </li>
    </ul>
      {%else%}
      <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Logged in as <strong>{{user}}</strong></a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{%url 'user:profile' id=user.id%}">Profile</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{%url 'user:sign_out'%}">Sign Out</a>
        </div>
      </li>
    </ul>
    {%endif%}
  </div>
</nav>

templates/dashboard/base.html
<!DOCTYPE html>
{%load staticfiles%}
{% load socialaccount %}
<html>
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<link rel="stylesheet"  href="{%static 'css/index.css'%}">

	<title></title>
</head>
<body>
{%include 'basic/navbar.html'%}
<section id="heading">
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="display-3">{%block title%}{%endblock%}</h1>
			 <p class="lead header-description">{%block description%}{%endblock%}</p>
			 <a href="{%url 'user:featured'%}" class="btn btn-dark btn-lg" role="button"><i class="fa fa-star"></i> Featured Agents</a>
		</div>
	
	</div>
</div>
</section>
{%block content%} {%endblock%}
<section id="footer">
	<i class="fa fa-facebook-f"></i>
    <i class="fa fa-twitter"></i>
    <i class="fa fa-linkedin"></i>
    <i class="fa fa-instagram"></i>
    <i class="fa fa-wechat"></i><br>
	© Copyright LetsRise 2019
</section>
</body>
</html>

templates/dashboard/home.html
{%extends 'dashboard/base.html'%}
{%load staticfiles%}
{% load socialaccount %}

{%block title%}Welcome to letsrise student's consultancy{%endblock%}
{%block description%}We help students from all over the world find scholarships in China at an affordable cost.{%endblock%}
{%block content%}


 <section id="features">
    <div class="row features-row">
    <div class="col-md-4">
    <i class="icon fa fa-star fa-4x"></i>  
    <h3>Cheap</h3>
    <p class="lead">Cheaper than our competitors</p>
    </div>
    <div class="col-md-4">
    <i class="icon fa fa-first-order fa-4x"></i> 
    <h3>Quick</h3>
    <p class="lead">Admission letter in 2 days</p>
    </div>
    <div class="col-md-4">
    <i class="icon fa fa-percent fa-4x"></i> 
    <h3>Services</h3>
    <p class="lead">Airport pickup, guidance etc</p>
    </div>
    </div>
  </section>

<section id="about">
	<div class="container">
		<p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque risus felis, luctus in purus maximus, venenatis fermentum diam. Suspendisse quis turpis eu neque tempor viverra ut eget tortor. Nam rutrum, ligula quis faucibus scelerisque, ante quam dapibus dolor, eget interdum quam enim a odio. Integer dolor quam, laoreet sed arcu a, efficitur sollicitudin orci. Sed auctor finibus purus, sed eleifend enim bibendum vel. Suspendisse tempus elementum nisi, vitae bibendum elit semper sit amet. Nulla dictum volutpat sapien, eu tincidunt justo placerat eu. Integer in ligula ac erat placerat fringilla ut id tortor. Maecenas molestie est vitae arcu scelerisque tempor nec vel nibh. Vestibulum tristique enim congue orci egestas, in interdum leo elementum. Curabitur tincidunt diam libero, quis interdum libero varius nec. Proin auctor suscipit eros a convallis. Etiam varius egestas blandit.</p>
	</div>
</section>
<section id="subscribe">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="display-3">Subscribe us for more information</h1>
				<form method="POST">
					{%csrf_token%}
  					<input type="text" class="form-control" placeholder="email"><br>
  					<button class="btn btn-dark btn-lg">Submit</button>
				</form>
			</div>
		</div>
	</div>
</section>
{%endblock%}

templates/dashboard/scholarship.html
{%extends 'dashboard/base.html'%}
{%load staticfiles%}
{% load socialaccount %}
{%block title%}Find a scholarship and apply!{%endblock%}
{%block description%}Verified scholarship from verified agents.{%endblock%}
{%block content%}
  <!-- Scholarships -->

<section id="pricing">
<div class="container pricing-container">
<div class="row">
	{%for scholarship in scholarships%}
  <div class="pricing-column col-lg-4  col-md-6">
    <div class="card h-100">

      <div class="card-header">
        <h5>{{scholarship.university}}</h5>
        <p class="lead"><strong class="agent-name">{{scholarship.university.city}}</strong></p>
      </div>
      <div class="card-body">
            {%if scholarship.schol_type == "P"%}<h4>Partial Scholarship</h4>{%else%}<h4>Full Scholarship</h4>{%endif%}
            <p><span>Tuition - </span> {{scholarship.tuition_after_schol}} RMB</p>
            <p><span>Accomodation - </span> {{scholarship.accomodation_after_schol}} RMB</p>
            <p><span>Stipend - </span> {{scholarship.stipend}} RMB</p>
            <p><span>Service charge - </span> ${{scholarship.service_charge}}</p><br>


      </div>
      <div class="user-buttons">
            <a href="{%url 'dashboard:scholarship_view' id=scholarship.id%}" class="btn btn-primary btn-lg" role="button">View Scholarship</a>
            <p><strong class="agent-name"><a href="{%url 'user:profile' id=scholarship.agent.user_detail.id%}">{{scholarship.agent}}</a></strong></p>
            </div>
    </div>
  </div>
   {%endfor%}
 
  </div>
  <div class="pagination">
    <span class="step-links">
        {% if scholarships.has_previous %}
            <a href="?page=1">&laquo; first</a> |
            <a href="?page={{ scholarships.previous_page_number }}">previous</a>
        {% endif %}
        <br>
        <span class="current">
            Page {{ scholarships.number }} of {{ scholarships.paginator.num_pages }}.
        </span>
        <br>
        {% if scholarships.has_next %}
            <a href="?page={{ scholarships.next_page_number }}">next</a> |
            <a href="?page={{ scholarships.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</div>
  </section>

{%endblock%}

templates/dashboard/scholarship_edit.html
{%extends 'dashboard/base.html'%}
{%load staticfiles%}
{% load socialaccount %}
{% load crispy_forms_tags %}
{%block title%}Welcome to letsrise student's consultancy{%endblock%}
{%block description%}We help students from all over the world find scholarships in China at an affordable cost.{%endblock%}
{%block content%}

<form method="POST">
{%csrf_token%}
{{form|crispy}}
<button class="btn btn-primary btn-lg float-right">Update</button>
</form>
{%endblock%}

templates/dashboard/scholarship_view.html
{%extends 'dashboard/base.html'%}
{%load staticfiles%}
{% load socialaccount %}
{%block title%}Apply now!{%endblock%}
{%block description%}Easy apply, View your agent, Click on apply now to submit your documents.{%endblock%}
{%block content%}
<div class="container university">
<img class="logo" src="{{university.logo.url}}">
<h1 class="scholarship-title">{{scholarship.university}}</h1><br>


<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Before Scholarship</th>
      <th scope="col">After Scholarship</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Tuition</th>
      <td>{{university.tuition}} RMB</td>
      <td>{{scholarship.tuition_after_schol}} RMB</td>
    </tr>
    <tr>
      <th scope="row">Accomodation</th>
      <td>{{university.accomodation}} RMB</td>
      <td>{{scholarship.accomodation_after_schol}} RMB</td>
    </tr>
    <tr>
      <th scope="row">Stipend</th>
      <td>0 RMB</td>
      <td>{{scholarship.stipend}} RMB</td>
    </tr>
    </tbody>
</table>
<br>
{{university.about}}<br><br>
<a href="{%url 'user:profile' id=scholarship.agent.user_detail.id%}" class="btn btn-primary btn-lg" role="button">View Agent</a>
<a href="" class="btn btn-outline-primary btn-lg" role="button">Apply Now</a>
</div>


{%endblock%}

templates/user/featured.html
{%extends 'dashboard/base.html'%}
{%load staticfiles%}
{% load socialaccount %}
{% load crispy_forms_tags %}
{%block title%}Agent Profile{%endblock%}
{%block description%}View the agent's profile details{%endblock%}
{%block content%}

{%if featured != None %}

	<section id="featured">
	<div class="container pricing-container">
	<div class="row">
		{%for account in featured%}
	  <div class="pricing-column col-lg-4 col-md-6">
	    <div class="card h-100">

	      <div class="card-header">
	        <img src="{{account.image.url}}">
	      </div>
	      <div class="card-body">
	            <h3>{{account.user}}</h3>	
	            <p class="lead">{{account.country}}</p>
	            <strong class="agent-name"><a href="{%url 'user:profile' id=account.id%}">Talk to me</a></strong>
	        {{scholarship.agent}}</a></strong>
	      </div>
	     
	    </div>
	  </div>
	   {%endfor%}
	 
	  </div>
	</div>
  </section>

{%else%}
<br>
<h3>No featured agents yet!</h3>
<br>
{%endif%}
{%endblock%}

templates/user/profile.html
{%extends 'dashboard/base.html'%}
{%load staticfiles%}
{% load socialaccount %}
{% load crispy_forms_tags %}
{%block title%}Agent Profile{%endblock%}
{%block description%}View the agent's profile details{%endblock%}
{%block content%}
<br>
<div class="profile">
<img src="{{details.image.url}}">
<h3 class="agent-name">{{details.user}}</h3>

<div class="container-profile">
	<div class="profile-heading" style="background-color: #333; margin-top: 0; width: 100%; color: white;">
		<p class="lead">Profile</p>
	</div>
	<p>User type : <strong>{% if details.user_type == "A" %}Agent{%else%}Student{%endif%}</strong></p>
	<p>Country : <strong>{{details.country}}</strong></p>
	{% if details.featured == True %}
		<p>Verified  <i class="icon fa fa-star icon-verified"></i> </p>
	{%endif%}
</div>
<div class="container-profile">
	<div class="profile-heading" style="background-color: #333; margin-top: 0; width: 100%; color: white;">
		<p class="lead">Students</p>
	</div>
	<p>Students applied : <strong>12</strong></p>
	<p>Success rate: <strong>97%</strong></p>
</div>
<div class="container-profile">
	<div class="profile-heading" style="background-color: #333; margin-top: 0; width: 100%; color: white;">
		<p class="lead">Scholarships</p>
	</div>
	<div class="agent-scholarships">
		
			<table class="table">
				  <thead class="thead-light">
				    <tr>
				      <th scope="col">#</th>
				      <th scope="col">University</th>
				      <th scope="col">Tuition</th>
				      <th scope="col">Accomodation</th>
				      <th scope="col">Stipend</th>
				    </tr>
				  </thead>
				  {%for scholarship in scholarships%}
				  <tbody>
				    <tr>
				      <th scope="row"><img src="{{scholarship.university.logo.url}}" style="width: 50px; height: auto"><br>
				      	{% if scholarship.agent.id == user.id %}
				      	<a href="{%url 'dashboard:scholarship_edit' id=scholarship.id%}">Edit</a>
				      	<a href="">Delete</a>
				      	{%endif%}
				      </th>
				      <td><a href="{%url 'dashboard:scholarship_view' id=scholarship.id%}">{{scholarship.university}}</a></td>
				      <td>{{scholarship.tuition_after_schol}} RMB</td>
				      <td>{{scholarship.accomodation_after_schol}} RMB</td>
				      <td>{{scholarship.stipend}} RMB</td>
				    </tr>
			</tbody>
			{%endfor%}
			</table>
		
	</div>
</div>
<div class="container-profile">
	<div class="profile-heading" style="background-color: #333; margin-top: 0; width: 100%; color: white;">
		<p class="lead">Contact</p>
	</div>
	<div class="icon-contact">
		<div class="contact">
			<i class="icon fa fa-wechat icon-verified fa-4x"></i>
		</div>
		<div class="contact">
			<i class="icon fa fa-instagram icon-verified fa-4x"></i>
		</div>
		<div class="contact">
			<i class="icon fa fa-facebook icon-verified fa-4x"></i>
		</div>
		<div class="contact">
			<i class="icon fa fa-phone icon-verified fa-4x"></i>
		</div>
	</div>
</div>

{%endblock%}

templates/user/signin.html
{%extends 'dashboard/base.html'%}
{%load staticfiles%}
{% load socialaccount %}
{% load crispy_forms_tags %}
{%block title%}Login to apply{%endblock%}
{%block description%}Upload your documents and apply with the click of a button{%endblock%}
{%block content%}

<div class="container login-container">
   <form class="form-signin" method="POST">
 	    <h1>Sign In</h1><br><br>
 	    {%csrf_token%}
	    {{form|crispy}}
	    <button class="btn btn-primary">Submit</button><br><br>
	    <a href="{% provider_login_url 'github' %}">Login using github</a>
    </form>
</div>

{%endblock%}